#!/usr/bin/env bash
# Polls GitHub for issues labeled "approved-for-claude" on this repo and runs
# a `claude -p` session against each one in an isolated git worktree.
#
# This is the only piece of the feature-requests flow that can touch this
# machine's shell/filesystem - the web app and backend never execute code
# directly. Approving a request in the app just adds a label; this script,
# which only you can start and which only acts on issues in this repo, is
# what actually "summons" Claude.
#
# Usage:
#   ./scripts/feature-request-worker.sh              # poll forever, 60s interval
#   ./scripts/feature-request-worker.sh --once        # process pending issues once and exit
#
# Requires: gh (authenticated), claude, git, running from inside this repo.

set -euo pipefail

REPO="IamTugy/recipes"
POLL_INTERVAL_SECONDS=60
LABEL_APPROVED="approved-for-claude"
LABEL_IN_PROGRESS="claude-in-progress"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKTREES_DIR="$REPO_ROOT/.worktrees"

cd "$REPO_ROOT"
mkdir -p "$WORKTREES_DIR"

process_issue() {
  local number="$1" title="$2" body="$3"
  local branch="claude/issue-$number"
  local worktree="$WORKTREES_DIR/issue-$number"

  echo "[feature-request-worker] Claiming issue #$number: $title"
  # Claim it first so a restart of this script never double-processes an issue.
  gh issue edit "$number" -R "$REPO" --remove-label "$LABEL_APPROVED" --add-label "$LABEL_IN_PROGRESS"

  if [ -d "$worktree" ]; then
    echo "[feature-request-worker] Worktree already exists at $worktree, reusing it"
  else
    git worktree add "$worktree" -b "$branch" main
  fi

  (
    cd "$worktree"
    local prompt
    prompt=$(cat <<EOF
Implement the feature request from GitHub issue #$number in this repository.

Title: $title

$body

Work in this branch ($branch). Follow the existing conventions in this
codebase (see CLAUDE.md if present). Run the relevant test suite and
linter before committing. Make focused commits with clear messages.
When done, leave the working tree clean (all changes committed).
EOF
)
    echo "[feature-request-worker] Running claude -p for issue #$number in $worktree"
    claude -p "$prompt"
  )

  echo "[feature-request-worker] Pushing branch and opening a PR for issue #$number"
  git -C "$worktree" push -u origin "$branch"
  local pr_url
  pr_url=$(gh pr create -R "$REPO" \
    --head "$branch" \
    --base main \
    --title "$title" \
    --body "Implements #$number, generated by \`claude -p\` via the feature-request worker.

Closes #$number." \
    2>&1 | tail -1) || pr_url="(PR creation failed - check $worktree manually)"

  gh issue comment "$number" -R "$REPO" --body "Claude has proposed a fix: $pr_url

Worktree left at \`$worktree\` on this machine for review/iteration."

  echo "[feature-request-worker] Done with issue #$number -> $pr_url"
}

run_once() {
  local issues
  issues=$(gh issue list -R "$REPO" --label "$LABEL_APPROVED" --state open --json number,title,body)
  local count
  count=$(echo "$issues" | python3 -c 'import json,sys; print(len(json.load(sys.stdin)))')

  if [ "$count" -eq 0 ]; then
    echo "[feature-request-worker] No approved issues pending."
    return
  fi

  echo "$issues" | python3 -c 'import json,sys
for issue in json.load(sys.stdin):
    print(f"{issue[\"number\"]}\t{issue[\"title\"]}\t{issue[\"body\"].replace(chr(10), chr(2))}")' \
  | while IFS=$'\t' read -r number title body_escaped; do
    body=$(echo "$body_escaped" | tr '\002' '\n')
    process_issue "$number" "$title" "$body" || echo "[feature-request-worker] FAILED on issue #$number, continuing"
  done
}

if [ "${1:-}" = "--once" ]; then
  run_once
else
  echo "[feature-request-worker] Polling $REPO for label '$LABEL_APPROVED' every ${POLL_INTERVAL_SECONDS}s. Ctrl-C to stop."
  while true; do
    run_once
    sleep "$POLL_INTERVAL_SECONDS"
  done
fi
