#!/usr/bin/env bash
# Polls GitHub for issues labeled "approved-for-claude" on this repo and runs
# a `claude -p` session against each one in an isolated git worktree.
#
# This is the only piece of the feature-requests flow that can touch this
# machine's shell/filesystem - the web app and backend never execute code
# directly. Approving a request in the app just adds a label; this script,
# which only you can start and which only acts on issues in this repo, is
# what actually "summons" Claude.
#
# Usage:
#   ./scripts/feature-request-worker.sh              # poll forever, 60s interval
#   ./scripts/feature-request-worker.sh --once        # process pending issues once and exit
#
# Requires: gh (authenticated), claude, git, running from inside this repo.
# Requires these labels to already exist on the repo: feature-request,
# approved-for-claude, claude-in-progress, claude-needs-input, claude-pr-open
# (gh issue edit fails if a label doesn't exist yet - create with
# `gh label create <name>` once).

set -euo pipefail

REPO="IamTugy/recipes"
POLL_INTERVAL_SECONDS=60
LABEL_APPROVED="approved-for-claude"
LABEL_IN_PROGRESS="claude-in-progress"
LABEL_NEEDS_INPUT="claude-needs-input"
LABEL_PR_OPEN="claude-pr-open"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKTREES_DIR="$REPO_ROOT/.worktrees"

cd "$REPO_ROOT"
mkdir -p "$WORKTREES_DIR"

process_issue() {
  local number="$1" title="$2" body="$3"
  local branch="claude/issue-$number"
  local worktree="$WORKTREES_DIR/issue-$number"

  echo "[feature-request-worker] Claiming issue #$number: $title"
  # Claim it first so a restart of this script never double-processes an issue.
  gh issue edit "$number" -R "$REPO" --remove-label "$LABEL_APPROVED" --add-label "$LABEL_IN_PROGRESS"

  if [ -d "$worktree" ]; then
    echo "[feature-request-worker] Worktree already exists at $worktree, reusing it"
  else
    git worktree add "$worktree" -b "$branch" main
  fi

  local claude_log="$worktree/.claude-output.log"
  (
    cd "$worktree"
    local prompt
    prompt=$(cat <<EOF
Implement the feature request from GitHub issue #$number in this repository.

Title: $title

$body

Work in this branch ($branch). Follow the existing conventions in this
codebase (see CLAUDE.md if present). Run the relevant test suite and
linter before committing. Make focused commits with clear messages.
When done, leave the working tree clean (all changes committed).

If you genuinely need a decision only the repo owner can make (choice
of external provider, a cost/billing tradeoff, an ambiguous or
conflicting requirement), do not guess and do not implement a partial
placeholder - stop and clearly state the question and the options
instead of writing code.
EOF
)
    echo "[feature-request-worker] Running claude -p for issue #$number in $worktree"
    # --dangerously-skip-permissions: this runs unattended with no TTY to answer
    # prompts. Safe here specifically because the worktree/branch is a throwaway
    # sandbox - Claude never touches the main checkout, and every result lands
    # as a PR for the owner to review before merging, never an auto-merge.
    claude -p "$prompt" --dangerously-skip-permissions 2>&1 | tee "$claude_log"
  )

  local commit_count
  commit_count=$(git -C "$worktree" rev-list --count main.."$branch")

  if [ "$commit_count" -eq 0 ]; then
    echo "[feature-request-worker] No commits from issue #$number - Claude needs input, not opening a PR"
    gh issue edit "$number" -R "$REPO" --remove-label "$LABEL_IN_PROGRESS" --add-label "$LABEL_NEEDS_INPUT"
    gh issue comment "$number" -R "$REPO" --body "Claude didn't make any changes and needs input to proceed:

\`\`\`
$(tail -40 "$claude_log")
\`\`\`

Answer in this issue, then re-approve (add the \`$LABEL_APPROVED\` label) to try again."
    echo "[feature-request-worker] Done with issue #$number -> needs input, see comment"
    return
  fi

  echo "[feature-request-worker] Pushing branch and opening a PR for issue #$number"
  git -C "$worktree" push -u origin "$branch"
  local pr_url
  pr_url=$(gh pr create -R "$REPO" \
    --head "$branch" \
    --base main \
    --title "$title" \
    --body "Implements #$number, generated by \`claude -p\` via the feature-request worker.

Closes #$number." \
    2>&1 | tail -1) || pr_url="(PR creation failed - check $worktree manually)"

  gh issue edit "$number" -R "$REPO" --remove-label "$LABEL_IN_PROGRESS" --add-label "$LABEL_PR_OPEN"
  gh issue comment "$number" -R "$REPO" --body "Claude has proposed a fix: $pr_url

Worktree left at \`$worktree\` on this machine for review/iteration."

  echo "[feature-request-worker] Done with issue #$number -> $pr_url"
}

run_once() {
  local issues
  issues=$(gh issue list -R "$REPO" --label "$LABEL_APPROVED" --state open --json number,title,body)
  local count
  count=$(echo "$issues" | python3 -c 'import json,sys; print(len(json.load(sys.stdin)))')

  if [ "$count" -eq 0 ]; then
    echo "[feature-request-worker] No approved issues pending."
    return
  fi

  echo "$issues" | python3 -c "
import json, sys
for issue in json.load(sys.stdin):
    print(f\"{issue['number']}\t{issue['title']}\t{issue['body'].replace(chr(10), chr(2))}\")" \
  | while IFS=$'\t' read -r number title body_escaped; do
    body=$(echo "$body_escaped" | tr '\002' '\n')
    process_issue "$number" "$title" "$body" || echo "[feature-request-worker] FAILED on issue #$number, continuing"
  done
}

if [ "${1:-}" = "--once" ]; then
  run_once
else
  echo "[feature-request-worker] Polling $REPO for label '$LABEL_APPROVED' every ${POLL_INTERVAL_SECONDS}s. Ctrl-C to stop."
  while true; do
    run_once
    sleep "$POLL_INTERVAL_SECONDS"
  done
fi
